### ISSUE TITLE
Though it not a REAL issue, though i wanna ask you about the code

### ISSUE THREAD

**Issue by brain-stackoverflowed** [cttg8217/Circles_in_Circles#1]
1. Is there any reason for stress effect?
2. In line 43, what is the mechanism to set the width parameter
3. Have you ever tried setting the width in line 43 to solve the problem explained in line 49?

**Comment by brain-stackoverflowed** [comment]
> 

꽤 잘만들었네요. 항상 배우고 갑니다

**Comment by cttg8217** [comment]
1. LP판 사진 같은 느낌(?)으로 밝아집니다.
2. 색이 0=검정 -> 255=흰색으로 변하는데 어두울수록 굵게 만들었습니다.
3. 원래 색에 따라 굵기를 다르게 한 것이 49번 줄의 문제를 해결하기 위해 구현한 것이 맞습니다. 그런데도 완전히 해결이 안 되었습니다.
